version: '3.8'

services:
  backend:
    build: .
    container_name: drug-order-system-backend
    working_dir: /usr/src/app
    ports:
      - "5000:5000"
    volumes:
      # Mounts the project directory from your machine into the container.
      # Any local file changes will be immediately reflected in the container.
      - .:/usr/src/app
    env_file:
      - .env
    restart: unless-stopped
    command: npm start
